#!/usr/bin/env bash
# looping using while loop
# it print "bad luck from China" for the 4th loop
# it prints "bad luck from Japan" for the 9th loop
# it prints "bad luck from Italy" for the 17th loop

number=1

while [ $number -le 20 ]
do
	echo "$number"
	case $number in
		"4") echo "bad luck from China";;
		"9") echo "bad luck from Japan";;
		"17") echo "bad luck from Italy";;
	esac
	((number++))
done	
